[package]
name = "tutorial1-window"
version = "0.2.0"
authors = [
    "Ben Hansen <bhbenjaminhansen@gmail.com>",
    "Zageron <hello@adambryant.ca>",
]
edition = "2018"

[[bin]]
name = "tutorial1-window"
path = "src/main.rs"

[dependencies]
winit = "0.23"
wgpu = "0.6"
